




.build/uno/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/sketch.ino[0m
	@/Library/Frameworks/Python.framework/Versions/2.7/bin/ino preproc  -o $@ $^


all : .build/uno/src/sketch.cpp
	@true

